get http://localhost:3000/users

###

DELETE http://localhost:3000/users/2 HTTP/1.1

###

POST http://localhost:3000/users
Content-Type: application/json

 {
    "email": "oom@mail.com",
    "name": "om",
    "password":"mot de passe",
    "role": "AUTHOR"
 }

###
PATCH http://localhost:3000/users
Content-Type:application/json

  {
    "id": 1,
    "email": "test@gmail.com",
    "name": "test",
    "password": "TEST",
    "role": "USER"
  }